/*
 * generated by Xtext 2.13.0
 */
package mkaos.ide

import com.google.inject.Guice
import mkaos.LanguageRuntimeModule
import mkaos.LanguageStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class LanguageIdeSetup extends LanguageStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new LanguageRuntimeModule, new LanguageIdeModule))
	}
	
}
