/**
 * generated by Xtext 2.10.0
 */
package mkaos.validation;

import mkaos.validation.AbstractLanguageValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class LanguageValidator extends AbstractLanguageValidator {
}
